# Dependabot will run on day 25 of each month at 01:38 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "38 1 25 * *"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "38 1 25 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/src-widgets"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "38 1 25 * *"
    open-pull-requests-limit: 15
    versioning-strategy: "increase"
